#!/bin/sh

# Use the Jamf Pro API to send macOS updates
# to computers listed in the deviceIds array
# identified by their id. maxDefferrals, 
# version, and updateAction can be changed 
# for your specific needs.
#
# Updated: 3.01.2022 @ Robjschroeder  

# Variables

# Add API credentials
username="apiUsername"
password="apiPassword"
URL="https://jamf.pro.com"

encodedCredentials=$( printf "${username}:${password}" | /usr/bin/iconv -t ISO-8859-1 | /usr/bin/base64 -i - )

# Generate an auth token
authToken=$( /usr/bin/curl "${URL}/uapi/auth/tokens" \
--silent \
--request POST \
--header "Authorization: Basic ${encodedCredentials}" )

# Parse authToken for token, omit expiration
token=$( /usr/bin/awk -F \" '{ print $4 }' <<< "$authToken" | /usr/bin/xargs )

curl --request POST \
     --url https://yourserver.jamfcloud.com/api/v1/macos-managed-software-updates/send-updates \
     --header 'Accept: application/json' \
     --header 'Content-Type: application/json' \
     --header '
     --data '
{
     "deviceIds": [
          "13",
          "14"
     ],
     "maxDeferrals": 3,
     "version": "12.2",
     "updateAction": "DOWNLOAD_AND_INSTALL"
}
'
