#!/bin/sh

# Use the Jamf Pro API to send macOS updates
# to computers listed in the deviceIds array
# identified by their id. maxDefferrals, 
# version, and updateAction can be changed 
# for your specific needs.
#
# Updated: 3.01.2022 @ Robjschroeder  
#
# Updated: 05.03.2022 @robjschroeder 
# Added a couple more parameters as Jamf added
# some additional functionality

# Variables

# Add API credentials
username="apiUsername"
password="apiPassword"
URL="https://jamf.pro.com"

# Update settings

# Allow users to defer the update the provided number of 
# times before macOS forces the update. If a value is 
# provided, the Software Update will use the InstallLater install action.
maxDeferrals=""

# If no value is provided, the version will default to latest version based 
# on device eligibility.
version=""

# If no value is provided, the skipVersionVerification will default to false. 
# If a value is provided, the specified version will be forced to complete 
# DownloadAndInstall install action.
skipVersionVerification=""

# ApplyMajorUpdate setting is available only when updating to the latest version 
# based on device eligibility. If no value is provided, the calculated latest version 
# will only include minor version updates. If a value is provided, the calculated latest 
# version will include minor and major version updates.
applyMajorUpdate=""

# If not set, forceRestart will default to false. Can only be true if using 
# the DownloadAndInstall install action and the devices the command is sent 
# to are on macOs 11 or higher. If true, the DownloadAndInstall action is performed, 
# a restart will be forced. MaxDeferral will be ignored if defined.
forceRestart=""

# MaxDeferral is ignored if using the DownloadOnly install action.
# Options: DOWNLOAD_ONLY or DOWNLOAD_AND_INSTALL
updateAction=""


encodedCredentials=$( printf "${username}:${password}" | /usr/bin/iconv -t ISO-8859-1 | /usr/bin/base64 -i - )

# Generate an auth token
authToken=$( /usr/bin/curl "${URL}/uapi/auth/tokens" \
--silent \
--request POST \
--header "Authorization: Basic ${encodedCredentials}" )

# Parse authToken for token, omit expiration
token=$( /usr/bin/awk -F \" '{ print $4 }' <<< "$authToken" | /usr/bin/xargs )

curl --request POST \
     --url ${URL}/api/v1/macos-managed-software-updates/send-updates \
     --header "Accept: application/json" \
     --header "Content-Type: application/json" \
     --header "Authorization: Bearer ${token}" \
     --data "
{
     "deviceIds": [
          "13",
          "14"
     ],
     "maxDeferrals": ${maxDeferrals},
     "version": "${version}",
     "skipVersionVerification": "${skipVersionVerification}",
     "applyMajorUpdate": "${applyMajorUpdate}",
     "forceRestart": "${forceRestart}",
     "updateAction": "${updateAction}"
}
"

exit 0
